language: node_js
node_js:
- node
deploy:
  api_key:
    secure: Hlwd8WMHw0KAClY3e9+8mp4ijQsiiktaSNkaRecmXPJgMMbF/iLPLL3hfKzsEUj0wFm/d/lkVUoQiDFJjWo1CbiKsh+RdW5sYjh2PlOU5FIDlqaKzpTtQxBYydkYMK9Yiw7u3C18bxWq/Ml7wzObiTYMHlO7rhNvUR3x668giE39L1Q4a2ksdDJAv22+2E1vVgQnkybzdCGMagNK+uR+uRbfA1qhidSLLxTej4YVtdPl8e4ICKYfwMjQ4Bg1zyWZH1TLRiJPWj/XSjT0fNlj0HLUAQfdYtjq535/9ThRfjuGkrr05m9DhGKLtOns9Yo8XotrBWpoV3wZMuam8ZBK1ot4i1WwAEu1PZihxoeyfUxcVF3n6pvi4/BZlxtlYyzxo5UBb8Z7zyLu6Di9bQmxMdCEBaslodqUK4w1UEYKTgRqwUXUF6EGEDlD4caOC67Kj0t5ukSKRLNVAWR1TUVYt1HhykThYGfibQqxXLNXYgvuYDcsQn4wIbSz2xK62KN7rdJQhrio20C2GtNEdOCRXhScSZ8gbhz8BSdCAGeVlh5aC/kadpx5Rx4YelT4TdJx2bDs9eXhvFf8XEQAWuFmhV87t+JSM9p3hM7LLmleb7Xtl25qMk2g3bryxBWpWbmUb1sbcNZfjUcqPne1DVY58PKhIUdjUaqSFFLNd6a9hCg=
